// <auto-generated />
#nullable enable
using System.Globalization;
using System.Resources;

namespace AlarmaApp.Resources.Strings;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "1.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class AppStrings
{
    private static ResourceManager? resourceMan;
    private static CultureInfo? resourceCulture;

    internal AppStrings()
    {
    }

    public static ResourceManager ResourceManager
    {
        get
        {
            resourceMan ??= new ResourceManager("AlarmaApp.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
            return resourceMan;
        }
    }

    public static CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    public static string BiometricPromptTitle =>
        ResourceManager.GetString("BiometricPromptTitle", resourceCulture) ?? "Authenticate";

    public static string BiometricPromptCancel =>
        ResourceManager.GetString("BiometricPromptCancel", resourceCulture) ?? "Cancel";
}

#nullable restore
